version: "3"

services:

  mariadb:
    image: mariadb:10.3.14
    volumes:
      - /bcm/mariadb:/var/lib/mysql
    networks:
      - bcmnet
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bcm
      MYSQL_USER: bcm
      MYSQL_PASSWORD: bcm
    ports:
    - "33020:33020"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  django: django
    build: ./
    image: django
    networks:
      - bcmnet
    env_file: .env/.django
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - /bcm/nginx:/var/log/nginx
    networks:
      - bcmnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  bcmnet:
