-- MySQL Script generated by MySQL Workbench
-- Wed 08 Jan 2020 09:45:44 AM +0330
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bcm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bcm` ;

-- -----------------------------------------------------
-- Schema bcm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bcm` ;
USE `bcm` ;

-- -----------------------------------------------------
-- Table `bcm`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`users` ;

CREATE TABLE IF NOT EXISTS `bcm`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `mobile_number` VARCHAR(12) NOT NULL,
  `email_address` VARCHAR(255) NULL,
  `hard_password` VARCHAR(300) NOT NULL,
  `role` ENUM('admin', 'standard') NOT NULL DEFAULT 'standard',
  `iban` VARCHAR(34) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`buildings` ;

CREATE TABLE IF NOT EXISTS `bcm`.`buildings` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `coordinate` POINT NOT NULL,
  PRIMARY KEY (`id`),
  SPATIAL INDEX `COORDINATE` (`coordinate`) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`units` ;

CREATE TABLE IF NOT EXISTS `bcm`.`units` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `buildings_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_units_buildings1_idx` (`buildings_id` ASC) VISIBLE,
  CONSTRAINT `fk_buildings_units1`
    FOREIGN KEY (`buildings_id`)
    REFERENCES `bcm`.`buildings` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`incomes_expenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`incomes_expenses` ;

CREATE TABLE IF NOT EXISTS `bcm`.`incomes_expenses` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `type` ENUM('income', 'expense') NOT NULL DEFAULT 'expense',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`payment_gateways`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`payment_gateways` ;

CREATE TABLE IF NOT EXISTS `bcm`.`payment_gateways` (
  `id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL,
  `credentials` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`payments` ;

CREATE TABLE IF NOT EXISTS `bcm`.`payments` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `status` ENUM('pending', 'approved', 'rejected', 'expired') NOT NULL DEFAULT 'pending',
  `payment_gateway_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_1_idx` (`payment_gateway_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_1`
    FOREIGN KEY (`payment_gateway_id`)
    REFERENCES `bcm`.`payment_gateways` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`requests` ;

CREATE TABLE IF NOT EXISTS `bcm`.`requests` (
  `id` INT UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_requests_1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_requests_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bcm`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`bill_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`bill_type` ;

CREATE TABLE IF NOT EXISTS `bcm`.`bill_type` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`bills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`bills` ;

CREATE TABLE IF NOT EXISTS `bcm`.`bills` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `payment_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `bill_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bills_1_idx` (`payment_id` ASC) VISIBLE,
  INDEX `fk_bills_2_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_bills_3_idx` (`bill_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_bills_1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `bcm`.`payments` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bills_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `bcm`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bills_3`
    FOREIGN KEY (`bill_type_id`)
    REFERENCES `bcm`.`bill_type` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`advertisements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`advertisements` ;

CREATE TABLE IF NOT EXISTS `bcm`.`advertisements` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `type` ENUM('local', 'global') NOT NULL DEFAULT 'local',
  `content` TEXT NOT NULL,
  `bill_id` BIGINT(20) UNSIGNED NOT NULL,
  `status` ENUM('rejected', 'approved', 'pending') NOT NULL DEFAULT 'pending',
  PRIMARY KEY (`id`),
  INDEX `fk_advertisements_1_idx` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `fk_advertisements_1`
    FOREIGN KEY (`bill_id`)
    REFERENCES `bcm`.`bills` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`settings` ;

CREATE TABLE IF NOT EXISTS `bcm`.`settings` (
  `key` VARCHAR(100) NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcm`.`users_units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcm`.`users_units` ;

CREATE TABLE IF NOT EXISTS `bcm`.`users_units` (
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `units_id` BIGINT(20) UNSIGNED NOT NULL,
  `type` ENUM('tenant', 'owner') NOT NULL DEFAULT 'owner',
  PRIMARY KEY (`users_id`, `units_id`),
  INDEX `fk_users_has_units_units1_idx` (`units_id` ASC) VISIBLE,
  INDEX `fk_users_has_units_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_units_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `bcm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_units_units1`
    FOREIGN KEY (`units_id`)
    REFERENCES `bcm`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
