# Generated by Django 3.0.2 on 2020-01-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residences',
            name='parent_residences',
            field=models.ForeignKey(blank=True, help_text='parent residences for this residences', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residences_parent', to='building.Residences', verbose_name='parent residences'),
        ),
    ]
