# Generated by Django 3.0.2 on 2020-01-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20200130_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('title', models.CharField(help_text='title for this facility', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='description for this facility', verbose_name='description')),
                ('type', models.CharField(choices=[('RESIDENCE', 'Residence'), ('ALL', 'All'), ('BLOCK', 'Block'), ('UNIT', 'Unit')], default='BLOCK', help_text='type of facilities', max_length=32, verbose_name='Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('area', models.DecimalField(decimal_places=2, help_text='area for this unit', max_digits=6, verbose_name='area')),
                ('population', models.PositiveIntegerField(help_text='population of this unit', verbose_name='population')),
                ('residences', models.ForeignKey(help_text='residences of this unit', on_delete=django.db.models.deletion.CASCADE, to='building.Residences', verbose_name='residences')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('second_title', models.CharField(help_text='second title for this facility unit', max_length=255, verbose_name='second title')),
                ('description', models.TextField(help_text='description for this facility unit', verbose_name='description')),
                ('facility', models.ForeignKey(help_text='facility for this facility unit', on_delete=django.db.models.deletion.CASCADE, to='building.Facilities', verbose_name='facility')),
                ('unit', models.ForeignKey(help_text='unit for this facility unit', on_delete=django.db.models.deletion.CASCADE, related_name='Facilities', to='building.Unit', verbose_name='unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facilities',
            name='units',
            field=models.ManyToManyField(help_text='units for this facilities', through='building.FacilityUnit', to='building.Unit', verbose_name='units'),
        ),
    ]
