# Generated by Django 3.0.2 on 2020-01-30 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0004_auto_20200130_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('role', models.CharField(help_text='role of board', max_length=255, verbose_name='role')),
                ('residence', models.ForeignKey(help_text='residence of board', on_delete=django.db.models.deletion.CASCADE, to='building.Residences', verbose_name='residence')),
                ('user', models.ForeignKey(help_text='user of board', on_delete=django.db.models.deletion.CASCADE, related_name='residences_board', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='residences',
            name='users_board',
            field=models.ManyToManyField(help_text='users board', through='building.BoardOfDirectors', to=settings.AUTH_USER_MODEL, verbose_name='users board'),
        ),
    ]
