# Generated by Django 3.0.2 on 2020-02-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_auto_20200210_1114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityResidenceAccessabilities',
            new_name='FacilityResidenceAccessability',
        ),
    ]
