# Generated by Django 3.0.2 on 2020-02-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0008_auto_20200210_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacilityResidenceAccessability',
            new_name='FacilityResidenceAccessibility',
        ),
    ]
