# Generated by Django 3.0.2 on 2020-02-10 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0009_auto_20200210_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('title', models.CharField(help_text='title for this facility', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='description for this facility', verbose_name='description')),
                ('type', models.CharField(choices=[('RESIDENCE', 'Residence'), ('ALL', 'All'), ('BLOCK', 'Block'), ('UNIT', 'Unit')], default='BLOCK', help_text='type of Facility', max_length=32, verbose_name='Type')),
                ('units', models.ManyToManyField(help_text='Units for this Facility', through='building.FacilityUnit', to='building.Unit', verbose_name='Units')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='facilityresidence',
            name='facility',
            field=models.ForeignKey(help_text='facility for this facility residence', on_delete=django.db.models.deletion.CASCADE, to='building.Facility', verbose_name='facility'),
        ),
        migrations.AlterField(
            model_name='facilityunit',
            name='facility',
            field=models.ForeignKey(help_text='facility for this facility unit', on_delete=django.db.models.deletion.CASCADE, to='building.Facility', verbose_name='facility'),
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
    ]
