# Generated by Django 3.0.2 on 2020-02-11 15:06

from django.conf import settings
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0010_auto_20200210_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=django_mysql.models.EnumField(choices=[('RESIDENCE', 'Residence'), ('ALL', 'All'), ('BLOCK', 'Block'), ('UNIT', 'Unit')], default='BLOCK', help_text='type of Facility', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='facilityresidenceaccessibility',
            name='type',
            field=django_mysql.models.EnumField(choices=[('PUBLIC', 'Public'), ('BLOCK', 'Block'), ('UNIT', 'Unit'), ('RESIDENCE', 'Residence')], help_text='choose type for this accessibility', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='type',
            field=django_mysql.models.EnumField(choices=[('BUILDING', 'Building'), ('COMPLEX', 'Complex'), ('LOCAL_SHOP', 'Local shop'), ('TOWN', 'Town')], default='BUILDING', help_text='type of this residence', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='users',
            field=models.ManyToManyField(help_text='users for Unit', through='building.UnitUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='unituser',
            name='type',
            field=django_mysql.models.EnumField(choices=[('RESIDENT', 'Resident'), ('BOTH', 'Both'), ('OWNER', 'Owner')], default='RESIDENT', help_text='type of user', verbose_name='type'),
        ),
    ]
