# Generated by Django 3.0.2 on 2020-02-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0011_auto_20200211_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='latitude for this location', null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, help_text='longitude for this location', null=True, verbose_name='longitude')),
            ],
        ),
        migrations.AlterField(
            model_name='facilityresidence',
            name='blocks',
            field=models.ManyToManyField(blank=True, help_text='blocks for this this facility residence', related_name='facility_residence', to='building.Block', verbose_name='blocks'),
        ),
        migrations.AlterField(
            model_name='facilityresidence',
            name='residence',
            field=models.ForeignKey(help_text='residence for this facility residence', on_delete=django.db.models.deletion.CASCADE, related_name='facility_residences', to='building.Residence', verbose_name='residence'),
        ),
    ]
