# Generated by Django 3.0.2 on 2020-02-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0012_auto_20200220_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='coordinate',
            field=models.ForeignKey(default=1, help_text='coordinate for this residence', on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='building.Location', verbose_name='coordinate'),
            preserve_default=False,
        ),
    ]
