# Generated by Django 3.0.2 on 2020-02-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_residence_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('phone', models.CharField(help_text='the phone number', max_length=16, verbose_name='phone')),
                ('description', models.TextField(blank=True, help_text='description', verbose_name='description')),
                ('unit', models.ForeignKey(help_text='unit for this phone', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='building.Unit', verbose_name='unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
