# Generated by Django 3.0.2 on 2020-03-27 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('building', '0014_unitphonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('bill_class', django_mysql.models.EnumField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', help_text='class', verbose_name='class')),
                ('type', django_mysql.models.EnumField(choices=[('ADVERTISEMENT', 'Advertisement'), ('BUDGET', 'Budget'), ('REQUEST', 'Request'), ('SETTLEMENT_REQUEST', 'Settlement request')], default='BUDGET', help_text='type of bill', verbose_name='type')),
                ('due_at', models.DateTimeField(help_text='due at', verbose_name='due at')),
                ('price', models.DecimalField(decimal_places=2, help_text='bill price', max_digits=10, verbose_name='price')),
                ('currency', django_mysql.models.EnumField(choices=[('IRR', 'IRR'), ('USD', 'USD')], default='IRR', help_text='bill currency', verbose_name='currency')),
                ('description', models.TextField(help_text='description of bill', verbose_name='description')),
                ('status_description', models.TextField(help_text='status description', verbose_name='status description')),
                ('status', django_mysql.models.EnumField(choices=[('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', help_text='status of bill', verbose_name='status')),
                ('user', models.ForeignKey(help_text='owner of bill', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('title', models.CharField(help_text='title for budget', max_length=64, verbose_name='title')),
                ('budget_class', django_mysql.models.EnumField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', help_text='budget class', verbose_name='class')),
                ('period', models.IntegerField(default=0, help_text='period of budget', verbose_name='period')),
                ('start_at', models.DateTimeField(help_text='start at this time', verbose_name='start at')),
                ('deadline_in_days', models.IntegerField(blank=True, help_text='deadline in days', null=True, verbose_name='deadline in days')),
                ('finish_at', models.DateTimeField(help_text='finish at this time', verbose_name='finish at')),
                ('due_at', models.DateTimeField(help_text='due at this time', verbose_name='due at')),
                ('price', models.DecimalField(decimal_places=2, help_text='price of budget', max_digits=10, verbose_name='price')),
                ('price_formula', models.TextField(help_text='price formula', verbose_name='price formula')),
                ('parameters', django_mysql.models.JSONField(default=dict, help_text='parameters of formula', verbose_name='parameters')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('name', models.CharField(help_text='name of payment gateway', max_length=255, verbose_name='name')),
                ('credentials', django_mysql.models.JSONField(default=dict, help_text='credentials', verbose_name='credentials')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('info', django_mysql.models.JSONField(default=dict, help_text='info', verbose_name='info')),
                ('status', django_mysql.models.EnumField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONFIRMED', 'Confirmed')], default='PENDING', help_text='status of payment', verbose_name='status')),
                ('bill', models.ForeignKey(help_text='bill', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='building.Bill', verbose_name='bill')),
                ('payer', models.ForeignKey(help_text='payer', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='payer')),
                ('payment_gateway', models.ForeignKey(help_text='payment gateway', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='building.PaymentGateway', verbose_name='payment gateway')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('type', django_mysql.models.EnumField(choices=[('GLOBAL', 'Global'), ('LOCAL', 'local')], default='LOCAL', help_text='type of advertisement', verbose_name='type')),
                ('content', models.TextField(help_text='content of advertisement', verbose_name='content')),
                ('status', django_mysql.models.EnumField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', help_text='status of advertisement', verbose_name='status')),
                ('description', models.TextField(help_text='text of advertisement', verbose_name='text')),
                ('bill', models.ForeignKey(help_text='bill of advertisement', on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='building.Bill', verbose_name='bill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountingTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='object creation time', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='object modification time', verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(help_text='object id', verbose_name='object id')),
                ('value', models.CharField(help_text='value', max_length=255, verbose_name='value')),
                ('bills', models.ManyToManyField(help_text='bills', related_name='accounting_targets', to='building.Bill', verbose_name='bills')),
                ('budgets', models.ManyToManyField(help_text='budgets', related_name='accounting_targets', to='building.Budget', verbose_name='budgets')),
                ('content_type', models.ForeignKey(help_text='content type', limit_choices_to=models.Q(models.Q(('app_label', 'building'), ('model', 'residence')), models.Q(('app_label', 'building'), ('model', 'block')), models.Q(('app_label', 'building'), ('model', 'unit')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
