# Generated by Django 3.0.2 on 2020-04-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('building', '0015_accountingtarget_advertisement_bill_budget_payment_paymentgateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingtarget',
            name='value',
        ),
        migrations.AlterField(
            model_name='accountingtarget',
            name='bills',
            field=models.ManyToManyField(blank=True, help_text='bills', null=True, related_name='accounting_targets', to='building.Bill', verbose_name='bills'),
        ),
        migrations.AlterField(
            model_name='accountingtarget',
            name='budgets',
            field=models.ManyToManyField(blank=True, help_text='budgets', null=True, related_name='accounting_targets', to='building.Budget', verbose_name='budgets'),
        ),
        migrations.AlterField(
            model_name='accountingtarget',
            name='content_type',
            field=models.ForeignKey(choices=[(13, 'residence'), (10, 'block'), (7, 'unit')], default=13, help_text='content type', limit_choices_to=models.Q(models.Q(('app_label', 'building'), ('model', 'residence')), models.Q(('app_label', 'building'), ('model', 'block')), models.Q(('app_label', 'building'), ('model', 'unit')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
