# Generated by Django 3.0.2 on 2020-06-11 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('building', '0017_auto_20200525_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='content',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.CharField(help_text='image of advertisement', max_length=300, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.CharField(blank=True, help_text='link of advertisement', max_length=300, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='accountingtarget',
            name='content_type',
            field=models.ForeignKey(help_text='content type', limit_choices_to=models.Q(models.Q(('app_label', 'building'), ('model', 'residence')), models.Q(('app_label', 'building'), ('model', 'block')), models.Q(('app_label', 'building'), ('model', 'unit')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, help_text='description of advertisement', verbose_name='description'),
        ),
    ]
