name: CI

on: [push]

jobs:
  deploy:

    steps:
    - uses: actions/checkout@v1

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.3.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to EC2
      run: |
        git push ssh://admin@development.ibillding.com/var/www/ibillding dev
    
    - name: Run post deploy script
      run: |
        npm install

                                           
