#name: CI
#
#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#    
#    steps:
#    - uses: actions/checkout@v1
#
#    - name: Add remote origin
#      run: |
#        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
#    - name: Deploy to Heroku
#      run: |
#        git push heroku master     
#
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        git push heroku master
                                           
