# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-17-62-80.us-east-2.compute.amazonaws.com
        username: admin
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
          script: |
            whoami
            ls -al

    # Set private key for SSH connection
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.3.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to EC2
      run: |
        git push ssh://admin@ec2-3-17-62-80.us-east-2.compute.amazonaws.com/var/www/ibillding dev
    
    - name: Run post deploy script
      run: |
        npm install