# Generated by Django 3.0.2 on 2020-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='financial_credit',
            field=models.DecimalField(decimal_places=2, help_text='financial credit for this user', max_digits=10, null=True, verbose_name='financial credit'),
        ),
    ]
